### ISSUE TITLE
Add mandatory review in main branch

### ISSUE THREAD

**Issue by SakshiShreya** [Van-sh/Grocery-Planner#17]
Can be done by @Van-sh only as he is owner of repo

- Go to Settings
- On left menu, click on branches
- Click on Add branch ruleset
- Add name of ruleset
- Enforcement Status -> `Active`
- Under `Target branches` -> Click `Add target` -> Click `Include by pattern` -> Write `main` -> Click `Add inclusion pattern`
- Enable these checkboxes -> 
  - Restrict deletions
  - Require a pull request before merging
  - Block force pushes
- Under **Require a pull request before merging**, Set Required Approvals to 1 and Enable `Dismiss stale pull request approvals when new commits are pushed` 
- Click on save

**Comment by Van-sh** [comment]
done
